### ISSUE TITLE
Reasoning behind all the choices

### ISSUE THREAD

**Issue by serapath** [g-div/nodeplate#2]
Very interesting :-)
But for most of the things you list there are several alternatives.
I wonder if it would make sense - maintaining this project - to list all the reasons why a certain choice was made or what's the thought behind.

**Comment by g-div** [comment]
I understand your point and I will maybe reason my choices in the future, but they are not immutable and anyone is welcome to suggest alternatives, so that we can discuss them together.
Feel free to fork this repo and to open as much pull requests/issues as you want :)

Some modules included in this boilerplate already explain why they should be preferred over other their alternatives, as for example in the [FAQ](https://github.com/sindresorhus/xo#faq) section of the `xo` readme, and I mostly agree with their statements, if I've added them.
It would maybe look redundant if I would add the same statements to my readme as well.
What do you think?
