### ISSUE TITLE
Git Hooks should be the other way around

### ISSUE THREAD

**Issue by flesler** [g-div/nodeplate#4]
I see you test on commits and lint (and test) on pushes.
What I always do, and see other do as well is lint on commits and test on pushes.

This is obviously subjective, but, the way I see it, sometimes one commits without pushing when tackling a large change to keep the changes manageable, the tests might not pass at that moment but there's no reason why the linting should fail.
Once the commits are ready to be pushed (and deployed) they MUST pass the tests ofc.

**Comment by flesler** [comment]
BTW, not entirely related to the issue but, have considered ghooks instead of husky? I'm interested in the reason why husky was picked if both were known. You could add that to the README, there's an opened issue about reasoning of choices

**Comment by g-div** [comment]
I'm actually linting and testing the code on pushes. The lint task could be eventually moved to the pre-commit hook. It would be better if tests pass on commit, so that you can deploy any commit  without breaking things...but yes, this is pretty subjective and depends on the git/deployment strategy used.

Actually I didn't know [gtramontina/ghooks](https://github.com/gtramontina/ghooks) and I will of course give it a try.
As far as I understand the main differences are:
**Usage**: 
- husky configuration goes in `npm scripts`
- ghooks configuration goes in `config.ghooks`

The advantage could be that husky hooks could be called from the CLI using `npm run precommit`, if needed.

**Supported hooks**:
- ghooks supports [all documented hooks](https://github.com/gtramontina/ghooks#all-documented-hooks-are-available)
- husky doesn't support _post-update_, _pre-auto-gc_ and _post-rewrite_ at the moment

Do you know any other feature/reason to prefer ghooks over husky ?

**Comment by flesler** [comment]
No, not really.

I like the npm script part, didn't have it mind.

**Comment by g-div** [comment]
Ok, then I will first close this issue. Feel free to re-open this or open a new issue, if you find other advantages of ghooks.
